### ISSUE TITLE
Equity fonts in repo

### ISSUE THREAD

**Issue by mbutterick** [thibaultmalfoy/thibaultmalfoy.github.io#1]
I know you have a paid license for my fonts (thank you) but I'm afraid the license doesn't permit public redistribution of the fonts through a GitHub repo.

**Comment by thibaultmalfoy** [comment]
I'm sorry. I'm fixing it right now.

**Comment by thibaultmalfoy** [comment]
Sorry again. I'm such a newbie here, and I didn't realize that this GitHub repo was public. Your fonts are no more available in this repo. I know it takes a long time to make them, and I don't want to ruin all the typographic economy, you can be sure of that. Best regards.
